trigger:
- main  # Puedes cambiar esto según la rama que desees desencadenar

pool:
  name: Default
  #vmImage: 'ubuntu-latest'

steps:
- script: |
    # Inicializar y aplicar Terraform
    cd path/to/terraform/config
    terraform init
    terraform destroy    
  displayName: 'Apply Terraform'
