trigger:
- main  # Puedes cambiar esto según la rama que desees desencadenar

pool:
  name: vmTerraform
  #vmImage: 'ubuntu-latest'

steps:
- script: |
    # Inicializar y aplicar Terraform
    cd path/to/terraform/config
    # terraform init
    terraform apply -auto-approve -destroy
    terraform apply -auto-approve
  displayName: 'Apply Terraform'
