trigger:
- main  # Puedes cambiar esto según la rama que desees desencadenar

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    # Instalar Terraform CLI
    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
    sudo apt-get update && sudo apt-get install terraform

    # Configurar credenciales de AWS
    export AWS_ACCESS_KEY_ID=$(aws_access_key)  # Reemplaza con el nombre de la variable
    export AWS_SECRET_ACCESS_KEY=$(aws_secret_access_key)  # Reemplaza con el nombre de la variable

    # Inicializar y aplicar Terraform
    cd path/to/terraform/config
    terraform init
    terraform apply -auto-approve
  displayName: 'Run Terraform'
